version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - my-app
  web:
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    working_dir: /var/www
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
    networks:
      - my-app

networks:
  my-app: